In [24]:
read_fix_list = open('POSCAR.vasp.bk', 'r')
xyz = read_fix_list.readlines()
read_fix_list.close()

In [25]:
xyz

['Au100bridge\n',
 '1.0\n',
 '       11.5352001190         0.0000000000         0.0000000000\n',
 '        0.0000000000        11.5352001190         0.0000000000\n',
 '        0.0000000000         0.0000000000        29.2740001678\n',
 '   Au    C    O\n',
 '  128    1    1\n',
 'Direct\n',
 '     0.000000000         0.000000000         0.069660001\n',
 '     0.000000000         0.000000000         0.219209999\n',
 '     0.000000000         0.000040000         0.368000001\n',
 '     0.000000000         0.000000000         0.515139997\n',
 '     0.125000000         0.125000000         0.000000000\n',
 '     0.125000000         0.124990001         0.144350007\n',
 '     0.125000000         0.125000000         0.293469995\n',
 '     0.124990001         0.125009999         0.441980004\n',
 '     0.250000000         0.000000000         0.069660001\n',
 '     0.250000000         0.999989986         0.219209999\n',
 '     0.250000000         0.999989986         0.368000001\n',
 '     0.249990

In [26]:
xyz = xyz[8:]

In [27]:
xyz

['     0.000000000         0.000000000         0.069660001\n',
 '     0.000000000         0.000000000         0.219209999\n',
 '     0.000000000         0.000040000         0.368000001\n',
 '     0.000000000         0.000000000         0.515139997\n',
 '     0.125000000         0.125000000         0.000000000\n',
 '     0.125000000         0.124990001         0.144350007\n',
 '     0.125000000         0.125000000         0.293469995\n',
 '     0.124990001         0.125009999         0.441980004\n',
 '     0.250000000         0.000000000         0.069660001\n',
 '     0.250000000         0.999989986         0.219209999\n',
 '     0.250000000         0.999989986         0.368000001\n',
 '     0.249990001         0.000000000         0.515129983\n',
 '     0.375000000         0.125000000         0.000000000\n',
 '     0.375000000         0.124990001         0.144350007\n',
 '     0.375010014         0.125000000         0.293469995\n',
 '     0.374989986         0.125000000         0.441980

In [28]:
read_z = [i.split()[2]  for i in xyz]

In [29]:
read_z

['0.069660001',
 '0.219209999',
 '0.368000001',
 '0.515139997',
 '0.000000000',
 '0.144350007',
 '0.293469995',
 '0.441980004',
 '0.069660001',
 '0.219209999',
 '0.368000001',
 '0.515129983',
 '0.000000000',
 '0.144350007',
 '0.293469995',
 '0.441980004',
 '0.069660001',
 '0.219209999',
 '0.368019998',
 '0.515139997',
 '0.000000000',
 '0.144350007',
 '0.293469995',
 '0.441980004',
 '0.069660001',
 '0.219209999',
 '0.368000001',
 '0.515129983',
 '0.000000000',
 '0.144350007',
 '0.293469995',
 '0.441969991',
 '0.069660001',
 '0.219209999',
 '0.368000001',
 '0.515139997',
 '0.000000000',
 '0.144350007',
 '0.293469995',
 '0.441969991',
 '0.069660001',
 '0.219200000',
 '0.367989987',
 '0.515139997',
 '0.000000000',
 '0.144350007',
 '0.293469995',
 '0.441980004',
 '0.069660001',
 '0.219200000',
 '0.368000001',
 '0.515139997',
 '0.000000000',
 '0.144350007',
 '0.293469995',
 '0.441980004',
 '0.069660001',
 '0.219200000',
 '0.367989987',
 '0.515139997',
 '0.000000000',
 '0.144350007',
 '0.2934

In [30]:
read_z = [float(i) for i in read_z]
import numpy as np
fix_list = np.unique(read_z)

In [31]:
fix_list

array([ 0.        ,  0.06966   ,  0.14435001,  0.2192    ,  0.21921   ,
        0.29346999,  0.29348001,  0.36798999,  0.368     ,  0.36802   ,
        0.44194999,  0.44196999,  0.44198   ,  0.51512998,  0.51514   ,
        0.58077002,  0.63080001])

In [32]:
fix_list = fix_list[:2]

In [33]:
fix_list

array([ 0.     ,  0.06966])

In [4]:
def read_fix_list(filename, n):
    read_fix_list = open(filename, 'r')
    xyz = read_fix_list.readlines()
    read_fix_list.close()
    xyz = xyz[8:]
    read_z = [float(i.split()[2])  for i in xyz]
    fix_list = np.unique(read_z)
    return fix_list[:n]

In [36]:
read_fix_list('POSCAR.vasp.bk', 2)

array([ 0.     ,  0.06966])

In [37]:
fp = open(source_file , 'r')
fp_fix = open(target_file , 'w')
fix_list =  read_fix_list(source_file, num_layer_fixed)
a=0
b=0
selected = 0
for line in fp:
	if b<7:
		fp_fix.write(line)
	elif b==7:
		if list(line.strip())[0] == 's' or list(line.strip())[0] == 'S':
			selected = 1
		else:
			selected = 0
			fp_fix.write('selective\n')
		fp_fix.write(line)
	else:
		if selected:
			fp_fix.write(line)
		else:
			fp_fix.write(line.rstrip())
			z=float(line.split()[2])
			if z in fix_list:
				fp_fix.write(' F F F \n')
				a+=1
			else:
				fp_fix.write(' T T T \n')
	b+=1
fp_fix.close()
fp.close()
print 'there are %d atoms fixed' % a

'__main__'

In [11]:
def fix_atom_slected(source_file, target_file, fix_list):
    fixed_atom_num = 0
    row_sign = 0
    selected = 0
    with open(source_file, mode = 'r') as initial_file:
        with open(target_file, mode = 'w') as finished_file:
            for line in initial_file:
                if row_sign < 7:
                    finished_file.write(line)
                elif row_sign == 7:
                    if list(line.strip())[0] == 's' or list(line.strip())[0] == 'S':
                        selected = 1
                    else:
                        selected = 0
                        finished_file.write('selective\n')
                    finished_file.write(line)
                else:
                    if selected:
                        finished_file.write(line)
                    else:
                        finished_file.write(line.rstrip())
                        z=float(line.split()[2])
                        if z in fix_list:
                            finished_file.write(' F F F \n')
                            fixed_atom_num +=1
                        else:
                            finished_file.write(' T T T \n')
                row_sign += 1
            print 'there are %d atoms fixed' % fixed_atom_num
        return target_file

In [12]:
import numpy as np

In [18]:
a = fix_atom_slected('POSCAR.vasp', 'POSCAR', read_fix_list('POSCAR.vasp', 4))

there are 7 atoms fixed


In [14]:
a

'POSCAR'

In [19]:

__name__

'__main__'

In [21]:
import numpy as np

def read_fix_list(filename, n):
    read_fix_list = open(filename, 'r')
    xyz = read_fix_list.readlines()
    read_fix_list.close()
    xyz = xyz[8:]
    read_z = [float(i.split()[2])  for i in xyz]
    fix_list = np.unique(read_z)
    return fix_list[:n]

def fix_atom_selected(source_file, target_file, fix_list):
    fixed_atom_num = 0
    row_sign = 0
    selected = 0
    with open(source_file, mode = 'r') as initial_file:
        with open(target_file, mode = 'w') as finished_file:
            for line in initial_file:
                if row_sign < 7:
                    finished_file.write(line)
                elif row_sign == 7:
                    if list(line.strip())[0] == 's' or list(line.strip())[0] == 'S':
                        selected = 1
                    else:
                        selected = 0
                        finished_file.write('selective\n')
                    finished_file.write(line)
                else:
                    if selected:
                        finished_file.write(line)
                    else:
                        finished_file.write(line.rstrip())
                        z=float(line.split()[2])
                        if z in fix_list:
                            finished_file.write(' F F F \n')
                            fixed_atom_num +=1
                        else:
                            finished_file.write(' T T T \n')
                row_sign += 1
            print 'there are %d atoms fixed' % fixed_atom_num
        return target_file
		
if __name__ == '__main__':
	num_layer_fixed = 2
	a = fix_atom_selected('POSCAR.vasp', 'POSCAR', read_fix_list('POSCAR.vasp', num_layer_fixed))

there are 5 atoms fixed
